config/routes.rb
Spree::Core::Engine.routes.prepend do
  match '/contact-us' => 'inquiries#index', :as => :contact

  resources :inquiries

  namespace :admin do
    resources :inquiries
  end

end

app/models/spree/inquiry.rb
class Spree::Inquiry < ActiveRecord::Base
  has_captcha
  validates :name ,:presence => true
  validates :email ,:presence => true
  validates :message ,:presence => true
   
  after_save :deliver_notification_email


  def deliver_notification_email
    ::Spree::InquiryMailer.notification(self).deliver
    # For delayed_job
    # InquiryMailer.send_later(:deliver_notification, self)
  end


end

app/controllers/spree/admin/inquiries_controller.rb
class Spree::Admin::InquiriesController < Spree::Admin::ResourceController

    layout 'spree/layouts/admin'


  def collection
    return @collection if @collection.present?
    unless request.xhr?
      @search = Spree::Inquiry.search(params[:search])

      #set order by to default or form result
      @search.order ||= "ascend_by_email"

      @collection = @search.page(params[:page]).per(Spree::Config[:orders_per_page])

    else
      @collection = Spree::Inquiry.find(:all, :limit => (params[:limit] || 100))
    end
  end

end

app/controllers/spree/inquiries_controller.rb
class Spree::InquiriesController < Spree::BaseController
  helper 'spree/base'
  
  def new
	  @inquiry = Spree::Inquiry.new()
  end
  
  def show
	  @inquiry = Spree::Inquiry.find_by_id(params[:id])
  end
  
  
  def create
    @inquiry = Spree::Inquiry.new(params[:inquiry])
    respond_to do |format|
      if @inquiry.save
        flash[:notice] = t(:on_send_message)
        format.html { redirect_to(@inquiry) }
      else
        format.html {  render :action => "new" }
      end
    end
  end

  #create.flash I18n.t(:on_send_message)

  def index
    redirect_to(new_inquiry_url) unless params[:inquiry]
  end

end

app/helpers/spree/admin/inquiries_helper.rb
module Spree::Admin::InquiriesHelper
end

app/helpers/spree/inquiries_helper.rb
module Spree::InquiriesHelper
  def translate_types
    INQUIRY_TYPES.collect { |i| t(i) }
  end
end

app/views/spree/admin/inquiries/index.html.erb
<h1><%= t("listing_inquiries") %></h1>
<h4><%= t(:admin_header_message) %></h4>

<table class="index">
    <thead>
    <tr>
        <%= hook :admin_inquiries_index_headers do %>
            <th><%= sort_link @search, :email, t("inquiry") %></th>
            <th>
                <%= hook :admin_inquiries_index_header_actions %>
            </th>
        <% end %>
    </tr>
    </thead>
    <tbody>
    <% @inquiries.each do |inquiry| %>
        <tr id="<%= dom_id inquiry %>">
            <%- locals = {:inquiry => inquiry} %>
            <%= hook :admin_inquiries_index_rows, locals do %>
                <td width="350px"><%= link_to inquiry.email, object_url(inquiry) %></td>
            <% end %>
            <td>
                <%= hook :admin_inquiries_index_row_actions, locals do %>
                    <%= link_to t(:display), object_url(inquiry) %> &nbsp;
                    <%= link_to_delete inquiry %>
                <% end %>
            </td>
        </tr>
    <% end %>
    </tbody>
</table>

<%= paginate(@inquiries, :previous_label => "&#171; #{t('previous')}", :next_label => "#{t('next')} &#187;") %>


<% content_for :sidebar do %>
    <div class="box">
        <h3><%= t(:search) %></h3>
        <%= form_for(@search ,:url => admin_inquiries_path,:method => :get) do |f| %>
            <%- locals = {:f => f} %>
            <%= hook :admin_inquiries_index_search, locals do %>
                <p>
                    <%= t("email") %><br/>
                    <%= f.text_field :email_contains, :size=>18 %>
                </p>
            <% end %>
            <%= hook :admin_inquiries_index_search_buttons, locals do %>
                <p><%= button t("search") %></p>
            <% end %>
        <% end %>
    </div>
<% end %>

app/views/spree/admin/inquiries/show.html.erb
<p>
    <%= t(:name) %>: <%= @inquiry.name %>
</p>
<p>
    <%= t(:email) %>: <%= @inquiry.email %>
</p>
<p>
    <%= t(:type) %>: <%= @inquiry.inquiry_type %>
</p>
<p>
    <%= "#{t(:order)} #{@inquiry.order_no}" unless @inquiry.order_no.blank? %>
</p>
<p>
    <%= t(:message) %>: <%= h @inquiry.message %>
</p>
<p>
    <%= link_to t(:back), collection_url %>
    | <%= button_to t("delete"), object_url(@inquiry), :confirm => t("confirm_delete"), :method => :delete %>
</p>
</tr>

app/views/spree/inquiries/new.html.erb
<% content_for :head do %>
  <%#= formtastic_stylesheet_link_tag %>
<% end %>

<% content_for :page_title do %>
  <%= @site_page.page_title rescue '' %>
<% end %>

<div class="contact_form">
  <%= form_for @inquiry do |form| %>

  <% if @inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inquiry.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @inquiry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <p><%= form.label :name %><br />
      <%= form.text_field :name, :required => true, :label => t(:your_name) %>
    </p>
    <p>
      <%= form.label :email %><br />
      <%= form.text_field :email, :required => true,:type => :email, :label => t(:your_email), :hint => t(:type_real_mail) %>
    </p>
    <p>
      <%= form.label :inquiry_type %><br />
      <%= form.select :inquiry_type, translate_types, :required => false %>
    </p>
    <p>
      <%= form.label :order_no %><br />
      <%= form.text_field :order_no, :label => t(:number_order), :required => false %>
    </p>
    <p>
      <%= form.label :message %><br />
      <%= form.text_area :message,:required => true, :label => t(:message) %>
    </p>
    <p>
      We need to make sure you're human! <br />
      <%=  form.label :captcha_solution, "What is #{@inquiry.captcha.task}" %> = ?
      <%= form.text_field :captcha_solution, :required => true%>
      <%= form.hidden_field :captcha_secret %>
    </p>
    <p>
      <%= form.submit 'Send', { :class => "styled-button long" } %>
    </p>
  <% end %>
</div>

app/views/spree/inquiries/show.html.erb
<% content_for :page_title do %>
    Thanks for getting in touch
<% end %>